spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081   # porta diversa da prod, così non confligge

enel:
  token: devToken123

bitrix24:
  url: https://demo.bitrix24.com/rest/1/devWebhook/crm.lead.add.json

logging:
  level:
    root: DEBUG
    com.example.enel_bitrix24_integration: DEBUG
