spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081   # porta diversa da prod, così non confligge

enel:
  api:
    base-url: https://api.enel.com/v1/
    auth-url: https://auth.enel.com/oauth/token
    client-id: ${ENEL_CLIENT_ID}
    client-jwt: ${ENEL_CLIENT_JWT}

bitrix24:
  url: ${BITRIX24_URL}

logging:
  level:
    root: DEBUG
    com.example.enel_bitrix24_integration: DEBUG
