server:
  port: 8080   # porta di default

spring:
  application:
    name: enel-bitrix24-integration

enel:
  api:
    base-url: https://api.enel.com/v1/
    auth-url: https://auth.enel.com/oauth/token
    client-id: ${ENEL_CLIENT_ID}
    client-jwt: ${ENEL_CLIENT_JWT}

bitrix24:
  url: ${BITRIX24_URL}


logging:
  level:
    root: INFO
    com.example.enel_bitrix24_integration: INFO