server:
  port: 8080   # porta di default

spring:
  application:
    name: enel-bitrix24-integration

enel:
  api:
    base-url: https://enel.in-voice.it
    auth-url: https://enel.in-voice.it/oauth2/token
    client-id: ${ENEL_CLIENT_ID}
    client-jwk: |
      {
          "kty": "RSA",
          "d": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "e": "AQAB",
          "n": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "alg": "RS256",
          "use": "sig",
          "kid": "my-key-id"
        }

bitrix24:
  api:
    base-url: https://b24-vayzx4.bitrix24.it/
    redirect-uri: https://b24-vayzx4.bitrix24.it/oauth/callback
    client-id: ${BITRIX_CLIENT_ID}
    client-jwk: ${BITRIX_CLIENT_JWK}



logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com.example.enel_bitrix24_integration: DEBUG